In [ ]:
# just replace numpy array and constants with tf tensors 
# rest is easy

In [1]:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf


In [ ]:
## basic linear algebra and stats with tensor flow

In [73]:
# generate random nd vector
# set random seed
tf.set_random_seed(0) 
norm = tf.random_normal([2, 3], mean=-1, stddev=4, seed = 0)

with tf.Session() as sess:
      
    print(sess.run(norm))
    

[[ -0.5043242   10.19509602  -8.18469143]
 [  0.2430383   -6.27797699  -1.20590532]]


In [98]:

# sum / diff of 2 nd vectors of the same size
# multiply vector with scalar
# multiply vector with vector - elem by elem
# '.' product of 2 vectors

tf.set_random_seed(0)

with tf.Session() as sess:
    
    x = tf.random_normal([2, 2], mean=-1, stddev=4, seed = 0)
    y = tf.random_normal([2, 2], mean=-1, stddev=4, seed = 0)
    
    z = x + y
    m = x*y
    add_scalar = x + 5
    
    dot_x_y = tf.matmul(x,y)
    
    a = sess.run({'x':x, 'y':y, 'z':z, 'm':m, 'add_scalar': add_scalar, 'dot_x_y': dot_x_y})
    # print shape sometimes for debugging
    print(dot_x_y.shape)

for key in a.keys():
    print(key)
    print(a[key])
    

(2, 2)
add_scalar
[[  4.49567604  15.19509602]
 [ -3.18469143   5.24303818]]
dot_x_y
[[-83.18937683  -2.66383481]
 [  2.13854456 -83.38465118]]
m
[[  2.54342884e-01   1.03939980e+02]
 [  6.69891739e+01   5.90676144e-02]]
y
[[ -0.5043242   10.19509602]
 [ -8.18469143   0.2430383 ]]
x
[[ -0.5043242   10.19509602]
 [ -8.18469143   0.2430383 ]]
z
[[ -1.0086484   20.39019203]
 [-16.36938286   0.48607659]]


In [2]:
# some constants stuff
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)
sess = tf.Session()
print(sess.run(total))


Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)
